### PR TITLE
Add Voltage to the Others page

### PR DESCRIPTION
**Pull request by gkrizek**
Thanks for creating this site! Very helpful for a lot of people. I'd like to propose adding in [Voltage](https://getvoltage.io) to the Others page as an additional way to get a Lightning node. Let me know if you have questions or think something should be reworded.

Thanks!

### CODE REVIEW

**Comment by BitcoinQnA** [comment]
Thank you

**Comment by shesek** [comment]
What does "doesn't have the ability to access user's funds or see transactions" mean exactly? Ultimately, whoever runs the hardware necessarily has the technical ability to access user funds and data, no?

**Comment by gkrizek** [comment]
@shesek this should help clarify things:
https://blog.getvoltage.io/how-voltage-works/

**Comment by shesek** [comment]
@gkrizek I read it, but still don't understand. The page says that Voltage can't access user data, but it doesn't explain how this is technically achieved.

**Pull request merged**
